version: "3"
services:
  host:
    container_name: recommendation-system-host
    networks:
      - recommendation-system
    image: nginx:alpine
    volumes:
      - ./public:/var/www/public
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - "db"
    depends_on:
      - "db"
    ports:
      - "8081:80"
    restart: on-failure

  app:
    container_name: recommendation-system-app
    networks:
      - recommendation-system
    build:
      dockerfile: ./Dockerfile
    volumes:
      - ./:/var/www
    links:
      - "db"
    depends_on:
      - "db"
    working_dir: /var/www
    restart: on-failure


  worker:
    container_name: recommendation-system-worker
    networks:
      - recommendation-system
    build:
      dockerfile: ./Dockerfile
    command: php artisan queue:work
    volumes:
      - ./:/var/www
    links:
      - "db"
    depends_on:
      - "db"
      - "app"
    working_dir: /var/www
    restart: on-failure



  db:
    container_name: recommendation-system-db
    networks:
      - recommendation-system
    image: mysql:8
    volumes:
      - recommendation_system_db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "33006:3306"
    restart: on-failure

    

volumes:
  recommendation_system_db:

networks:
  recommendation-system:
